"""
    Glenn.jl — Thermochemical Properties Calculator for Julia.

Computes Cp(T), H°(T), S°(T) from NASA-7 polynomial coefficients
stored in a SQLite database (`thermo.db`).

The database is the same `thermo.db` generated by the `pyglenn` Python package.
No conversion or parsing is performed — simply point to the database file.

# Quick Start

```julia
using Glenn

# Calculator() uses the bundled thermo.db automatically
calc = Calculator()

# Find the exact species (filter by name)
species = get_available_species(calc, "O2")
o2 = only(s for s in species if s["name"] == "O2")

# Calculate Cp, H°, S° at 1000 K
props = calculate_properties(calc, o2["id"], 1000.0)
println("Cp = ", round(props["cp"], digits=2), " J/(mol·K)")
println("H° = ", round(props["h_relative"], digits=1), " J/mol")
println("S° = ", round(props["s"], digits=3), " J/(mol·K)")

close(calc)
```
"""
module Glenn

# ------------------------------------------------------------------
# Submodules
# ------------------------------------------------------------------
include("database.jl")    # SQLite queries & NASA-7 polynomial math
include("calculator.jl")  # High-level calculation API

# Bring all public symbols into Glenn namespace
# ------------------------------------------------------------------

# Constants & types
const R_UNIVERSAL = ThermoDatabase.R_UNIVERSAL
const Calculator = ThermoCalculator.Calculator

# Database functions
using .ThermoDatabase: find_species, list_species_page, list_all_species,
    get_species_data, get_species_info, get_species_for_temperature,
    get_statistics, calculate_cp, calculate_h, calculate_s

# Calculator functions (high-level API)
using .ThermoCalculator: get_available_species, calculate_properties,
    calculate_formation_enthalpy, calculate_enthalpy_change,
    get_properties_range, default_db_path

# ------------------------------------------------------------------
# Exports (public API)
# ------------------------------------------------------------------

export Calculator
export R_UNIVERSAL
export default_db_path

export find_species, list_species_page, list_all_species,
       get_species_data, get_species_info, get_species_for_temperature,
       get_statistics, calculate_cp, calculate_h, calculate_s

export get_available_species, calculate_properties,
       calculate_formation_enthalpy, calculate_enthalpy_change,
       get_properties_range

end # module Glenn
